# Generated by Django 4.0.6 on 2022-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('cedula', models.IntegerField()),
                ('fechaNac', models.DateField()),
                ('email', models.EmailField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
